[virtualenvs]
in-project = true
path = ".venv"
create = true

[installer]
allow-external-executables = true

[build]
generate-setup-file = true

[repositories]

[repositories.pypi]
url = "https://upload.pypi.org/legacy/"

[repositories.testpypi]
url = "https://test.pypi.org/legacy/"
