version: '3'

services:
  getllm-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8002:8002"
    volumes:
      - ./tests:/app/tests
      - ./test-reports:/app/test-reports
    environment:
      - PORT=8002
      - HOST=0.0.0.0
      - DEBUG=True
    command: |
      bash -c "python -m pytest tests/ -v --junitxml=/app/test-reports/test-results.xml"

  getllm-mock:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8002:8002"
    volumes:
      - ./tests:/app/tests
      - ./test-reports:/app/test-reports
    environment:
      - PORT=8002
      - HOST=0.0.0.0
      - DEBUG=True
    command: |
      bash -c "python -m getllm.app --port 8002 --host 0.0.0.0"

volumes:
  test-reports:
