name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest pytest-cov
          
      - name: Check if run_docker_tests.sh exists
        id: check_script
        run: |
          if [ -f run_docker_tests.sh ]; then
            echo "script_exists=true" >> $GITHUB_OUTPUT
          else
            echo "script_exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Run tests with Docker
        if: steps.check_script.outputs.script_exists == 'true'
        run: bash run_docker_tests.sh
        
      - name: Run tests without Docker
        if: steps.check_script.outputs.script_exists != 'true'
        run: |
          pytest tests/ --cov=getllm
          
      - name: Prepare artifact directory
        run: |
          mkdir -p artifact
          cp -r getllm tests scripts *.md *.toml *.sh *.svg *.ini *.example Makefile Dockerfile* LICENSE artifact/ || true
          # Don't copy .pypirc as it may contain sensitive information
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact
          retention-days: 7
